travis:
  secure:
    BINSTAR_TOKEN: Ue9p9gTF6nLfdaywMPeOa4xhiQxuialapZvPVDG180H68zeiWvOo3REtwAI1V4hkBvoitgpuZ39LPKrv7wnfYkVlFIMyhUjY9T0GDJgDlGPMPj6YD6Z0wDSZ1+4y+YcUJV9zX3YoCJ2rvtfFCy/sS3cLF08Fn2BHX92pLlL/v0eE3RWqOhFeAqusJzEzxE2kfwoKjX9FyVDovbdsfgRPZ4KFPhgwBMD4pY8pYBC4mj9Di5P0EOXp4bGbIWIoCYI6VldhguYID1S7XmuSMVXeub5lok5pZ3XbqA5r3rZyGKPMCK8izlO6xVe4NovlMSPLfY+PwXWeW8fc0QYmgpSrElHlBZO74pS+yPBhSgolrc0WuBHgi6qE6q7h4G7YH7pK3/p49xY2MKcDRTA11yzmiV/FPUC95ABHBfi5LKywigfi6TwUGJmmlWqVjIo/aEkCGKvOebnlJVdlkIOC/N9ixIzl2ckgSMLL6Iau9rbpOrs+EpcLVJeKPOKaDGgy4FHxyu298SCuebzoh3+AdVnKXlxf/b3DXXp9b9t6crL4NZnBeaBt7wC9S7Nm7hQnXvQYUXG8SYq1koI+zODsyEW0XQvey87NqglGCdM35dQNov3uxaYN+toapspHYQhvRDz+c4CFhFXKXDSzah8m3An/8CtH4EsAzqM1piC9jjqvjSg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
